/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.github.mistertea.boardgame.landshark;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum PropertyType implements org.apache.thrift.TEnum {
  STREET(0),
  AUCTIONHOUSE(1),
  UTILITY(2),
  START(3),
  TAXES(4),
  EMPTY(5);

  private final int value;

  private PropertyType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static PropertyType findByValue(int value) { 
    switch (value) {
      case 0:
        return STREET;
      case 1:
        return AUCTIONHOUSE;
      case 2:
        return UTILITY;
      case 3:
        return START;
      case 4:
        return TAXES;
      case 5:
        return EMPTY;
      default:
        return null;
    }
  }
}
