/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.github.mistertea.boardgame.landshark;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TurnState implements org.apache.thrift.TEnum {
  START_GAME(0),
  ROLLING_DICE(1),
  ASK_AUCTION(2),
  ASK_ANY_AUCTION(3),
  FORCE_AUCTION(4),
  BUYING_HOUSES(5),
  AUCTION(6),
  AUCTION_RESULTS(7),
  PAYING_RENT(8);

  private final int value;

  private TurnState(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TurnState findByValue(int value) { 
    switch (value) {
      case 0:
        return START_GAME;
      case 1:
        return ROLLING_DICE;
      case 2:
        return ASK_AUCTION;
      case 3:
        return ASK_ANY_AUCTION;
      case 4:
        return FORCE_AUCTION;
      case 5:
        return BUYING_HOUSES;
      case 6:
        return AUCTION;
      case 7:
        return AUCTION_RESULTS;
      case 8:
        return PAYING_RENT;
      default:
        return null;
    }
  }
}
