/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.github.mistertea.boardgame.core;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (1.0.0-dev)", date = "2014-1-15")
public class DieRoll implements org.apache.thrift.TBase<DieRoll, DieRoll._Fields>, java.io.Serializable, Cloneable, Comparable<DieRoll> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DieRoll");

  private static final org.apache.thrift.protocol.TField NUM_DICE_FIELD_DESC = new org.apache.thrift.protocol.TField("numDice", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField DIE_SIZE_FIELD_DESC = new org.apache.thrift.protocol.TField("dieSize", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField MODIFIER_FIELD_DESC = new org.apache.thrift.protocol.TField("modifier", org.apache.thrift.protocol.TType.I32, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new DieRollStandardSchemeFactory());
    schemes.put(TupleScheme.class, new DieRollTupleSchemeFactory());
  }

  public int numDice; // required
  public int dieSize; // required
  public int modifier; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    NUM_DICE((short)1, "numDice"),
    DIE_SIZE((short)2, "dieSize"),
    MODIFIER((short)3, "modifier");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // NUM_DICE
          return NUM_DICE;
        case 2: // DIE_SIZE
          return DIE_SIZE;
        case 3: // MODIFIER
          return MODIFIER;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __NUMDICE_ISSET_ID = 0;
  private static final int __DIESIZE_ISSET_ID = 1;
  private static final int __MODIFIER_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.NUM_DICE, new org.apache.thrift.meta_data.FieldMetaData("numDice", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.DIE_SIZE, new org.apache.thrift.meta_data.FieldMetaData("dieSize", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.MODIFIER, new org.apache.thrift.meta_data.FieldMetaData("modifier", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DieRoll.class, metaDataMap);
  }

  public DieRoll() {
  }

  public DieRoll(
    int numDice,
    int dieSize,
    int modifier)
  {
    this();
    this.numDice = numDice;
    setNumDiceIsSet(true);
    this.dieSize = dieSize;
    setDieSizeIsSet(true);
    this.modifier = modifier;
    setModifierIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public DieRoll(DieRoll other) {
    __isset_bitfield = other.__isset_bitfield;
    this.numDice = other.numDice;
    this.dieSize = other.dieSize;
    this.modifier = other.modifier;
  }

  public DieRoll deepCopy() {
    return new DieRoll(this);
  }

  @Override
  public void clear() {
    setNumDiceIsSet(false);
    this.numDice = 0;
    setDieSizeIsSet(false);
    this.dieSize = 0;
    setModifierIsSet(false);
    this.modifier = 0;
  }

  public int getNumDice() {
    return this.numDice;
  }

  public DieRoll setNumDice(int numDice) {
    this.numDice = numDice;
    setNumDiceIsSet(true);
    return this;
  }

  public void unsetNumDice() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __NUMDICE_ISSET_ID);
  }

  /** Returns true if field numDice is set (has been assigned a value) and false otherwise */
  public boolean isSetNumDice() {
    return EncodingUtils.testBit(__isset_bitfield, __NUMDICE_ISSET_ID);
  }

  public void setNumDiceIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __NUMDICE_ISSET_ID, value);
  }

  public int getDieSize() {
    return this.dieSize;
  }

  public DieRoll setDieSize(int dieSize) {
    this.dieSize = dieSize;
    setDieSizeIsSet(true);
    return this;
  }

  public void unsetDieSize() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __DIESIZE_ISSET_ID);
  }

  /** Returns true if field dieSize is set (has been assigned a value) and false otherwise */
  public boolean isSetDieSize() {
    return EncodingUtils.testBit(__isset_bitfield, __DIESIZE_ISSET_ID);
  }

  public void setDieSizeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __DIESIZE_ISSET_ID, value);
  }

  public int getModifier() {
    return this.modifier;
  }

  public DieRoll setModifier(int modifier) {
    this.modifier = modifier;
    setModifierIsSet(true);
    return this;
  }

  public void unsetModifier() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __MODIFIER_ISSET_ID);
  }

  /** Returns true if field modifier is set (has been assigned a value) and false otherwise */
  public boolean isSetModifier() {
    return EncodingUtils.testBit(__isset_bitfield, __MODIFIER_ISSET_ID);
  }

  public void setModifierIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __MODIFIER_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case NUM_DICE:
      if (value == null) {
        unsetNumDice();
      } else {
        setNumDice((Integer)value);
      }
      break;

    case DIE_SIZE:
      if (value == null) {
        unsetDieSize();
      } else {
        setDieSize((Integer)value);
      }
      break;

    case MODIFIER:
      if (value == null) {
        unsetModifier();
      } else {
        setModifier((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case NUM_DICE:
      return Integer.valueOf(getNumDice());

    case DIE_SIZE:
      return Integer.valueOf(getDieSize());

    case MODIFIER:
      return Integer.valueOf(getModifier());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case NUM_DICE:
      return isSetNumDice();
    case DIE_SIZE:
      return isSetDieSize();
    case MODIFIER:
      return isSetModifier();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof DieRoll)
      return this.equals((DieRoll)that);
    return false;
  }

  public boolean equals(DieRoll that) {
    if (that == null)
      return false;

    boolean this_present_numDice = true;
    boolean that_present_numDice = true;
    if (this_present_numDice || that_present_numDice) {
      if (!(this_present_numDice && that_present_numDice))
        return false;
      if (this.numDice != that.numDice)
        return false;
    }

    boolean this_present_dieSize = true;
    boolean that_present_dieSize = true;
    if (this_present_dieSize || that_present_dieSize) {
      if (!(this_present_dieSize && that_present_dieSize))
        return false;
      if (this.dieSize != that.dieSize)
        return false;
    }

    boolean this_present_modifier = true;
    boolean that_present_modifier = true;
    if (this_present_modifier || that_present_modifier) {
      if (!(this_present_modifier && that_present_modifier))
        return false;
      if (this.modifier != that.modifier)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(DieRoll other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetNumDice()).compareTo(other.isSetNumDice());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNumDice()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.numDice, other.numDice);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDieSize()).compareTo(other.isSetDieSize());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDieSize()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dieSize, other.dieSize);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetModifier()).compareTo(other.isSetModifier());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetModifier()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.modifier, other.modifier);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("DieRoll(");
    boolean first = true;

    sb.append("numDice:");
    sb.append(this.numDice);
    first = false;
    if (!first) sb.append(", ");
    sb.append("dieSize:");
    sb.append(this.dieSize);
    first = false;
    if (!first) sb.append(", ");
    sb.append("modifier:");
    sb.append(this.modifier);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class DieRollStandardSchemeFactory implements SchemeFactory {
    public DieRollStandardScheme getScheme() {
      return new DieRollStandardScheme();
    }
  }

  private static class DieRollStandardScheme extends StandardScheme<DieRoll> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, DieRoll struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // NUM_DICE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.numDice = iprot.readI32();
              struct.setNumDiceIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DIE_SIZE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.dieSize = iprot.readI32();
              struct.setDieSizeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // MODIFIER
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.modifier = iprot.readI32();
              struct.setModifierIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, DieRoll struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(NUM_DICE_FIELD_DESC);
      oprot.writeI32(struct.numDice);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(DIE_SIZE_FIELD_DESC);
      oprot.writeI32(struct.dieSize);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(MODIFIER_FIELD_DESC);
      oprot.writeI32(struct.modifier);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DieRollTupleSchemeFactory implements SchemeFactory {
    public DieRollTupleScheme getScheme() {
      return new DieRollTupleScheme();
    }
  }

  private static class DieRollTupleScheme extends TupleScheme<DieRoll> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, DieRoll struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetNumDice()) {
        optionals.set(0);
      }
      if (struct.isSetDieSize()) {
        optionals.set(1);
      }
      if (struct.isSetModifier()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetNumDice()) {
        oprot.writeI32(struct.numDice);
      }
      if (struct.isSetDieSize()) {
        oprot.writeI32(struct.dieSize);
      }
      if (struct.isSetModifier()) {
        oprot.writeI32(struct.modifier);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, DieRoll struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.numDice = iprot.readI32();
        struct.setNumDiceIsSet(true);
      }
      if (incoming.get(1)) {
        struct.dieSize = iprot.readI32();
        struct.setDieSizeIsSet(true);
      }
      if (incoming.get(2)) {
        struct.modifier = iprot.readI32();
        struct.setModifierIsSet(true);
      }
    }
  }

}

