/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.github.mistertea.boardgame.core;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ServerMessageType implements org.apache.thrift.TEnum {
  ERROR(0),
  CHAT(1),
  NEW_STATE(2);

  private final int value;

  private ServerMessageType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ServerMessageType findByValue(int value) { 
    switch (value) {
      case 0:
        return ERROR;
      case 1:
        return CHAT;
      case 2:
        return NEW_STATE;
      default:
        return null;
    }
  }
}
